#!/bin/bash

set -euo pipefail
set -x

if [[ $EUID -eq 0 ]]; then
  echo "Don't run as root" >&2
  exit 1
fi

readonly channel="${1:-stable}"
version="${2:-current}"
if [[ "${version}" == "current" ]]; then
  version="$(curl -fsSL https://"${channel}".release.flatcar-linux.net/amd64-usr/current/version.txt | awk '/FLATCAR_VERSION=/ { split($0,a,"="); print a[2] }')"
fi
declare -r version
readonly name_alias="${3:-flatcar-${channel}-${version}}"

readonly work_dir="flatcar-lxd-image-${channel}-${version}"

mkdir -p "${work_dir}"
pushd "${work_dir}"
trap "popd" EXIT

# https://kinvolk.io/flatcar-container-linux/security/image-signing-key/
curl -fsSL https://kinvolk.io/flatcar-container-linux/security/image-signing-key/Flatcar_Image_Signing_Key.asc | gpg --import

curl -fsSLO "https://${channel}.release.flatcar-linux.net/amd64-usr/${version}/flatcar_production_qemu_image.img.bz2"
curl -fsSLO "https://${channel}.release.flatcar-linux.net/amd64-usr/${version}/flatcar_production_qemu_image.img.bz2.sig"

gpg --verify flatcar_production_qemu_image.img.bz2.sig flatcar_production_qemu_image.img.bz2

cat >metadata.yaml <<EOF
architecture: x86_64
creation_date: $(date +%s)
properties:
  description: Flatcar ${channel}
  os: Flatcar
  release: ${version}
EOF

tar -czvf metadata.tar.gz metadata.yaml

bunzip2 flatcar_production_qemu_image.img.bz2

# Only files with qcow2 suffix are imported as "type: virtual-machine" by lxd
mv flatcar_production_qemu_image.img flatcar_production_qemu_image.qcow2

lxc image import metadata.tar.gz flatcar_production_qemu_image.qcow2 --alias "${name_alias}"

cat <<EOF

==> Added image 'flatcar-${channel}-${version}'
==> Example launch command:

lxc launch flatcar-${channel}-${version} v1 --config security.secureboot=false

==> Example attach command:

lxc console v1

EOF

exit 0
